"""One-line purpose of each endpoint, injected into the OpenAPI schema (shown at /docs, /api and in API.md)."""
DESCRIPTIONS = {
    ("get", "/api/health"): "Server status: database, schema version, data mode, pipeline and model versions, counts",
    ("get", "/api/meta"): "Areas, report categories and statuses, tanker sizes, reuse categories",
    ("get", "/api/areas"): "v1 compatibility: areas and categories",
    ("get", "/api/overview"): "Dashboard in one call: risk score, warnings, all indicators with provenance",
    ("get", "/api/risk/current"): "Current water-risk score, level and weighted components (stores a snapshot when inputs change)",
    ("get", "/api/risk/explanation"): "Why the score is what it is: formula, weights, anchors, plain-language drivers",
    ("get", "/api/risk/history"): "Stored risk-score snapshots, newest first",
    ("get", "/api/warnings"): "Early warnings from the rule engine: level, trigger, indicator, time, actions",
    ("get", "/api/signals"): "v1 compatibility: rain, reservoirs and groundwater in the old shape",
    ("get", "/api/rainfall"): "Current season departures plus 1901–2015 climatology, trend, Mann-Kendall test, driest seasons",
    ("get", "/api/rainfall/history"): "Season rows (and optionally monthly rows with anomalies) for a year range",
    ("get", "/api/reservoirs"): "Latest reading per reservoir with trend and risk contribution",
    ("get", "/api/reservoirs/history"): "All reservoir readings (pipeline + admin uploads)",
    ("get", "/api/reservoirs/{rid}"): "One reservoir with its full history",
    ("get", "/api/groundwater"): "Official extraction stage (real) vs modelled city water balance, stress score",
    ("get", "/api/lakes"): "Lakes with location provenance, ward and number of quality observations; city lake summary",
    ("get", "/api/lakes/{lake_id}"): "One lake with its admin-added quality observations",
    ("get", "/api/gis/wards"): "243 BBMP ward polygons (GeoJSON, simplified)",
    ("get", "/api/gis/layers"): "Map layer sources, locality points, and what ward-level data is unavailable",
    ("get", "/api/water-quality"): "IS 10500:2012 limits for the 18 parameters",
    ("post", "/api/water-quality/check"): "Classify lab values as Safe / High / Unsafe against IS 10500:2012",
    ("post", "/api/rwh"): "Rainwater harvesting: BWSSB rule, storage, monthly and yearly harvest, penalty avoided",
    ("get", "/api/forecast"): "Next-month rainfall forecast with the evaluation behind the chosen model",
    ("get", "/api/forecast/backtest"): "Out-of-sample forecasts vs actual rainfall (test period 1996–2015)",
    ("post", "/api/ml/predict"): "Deficient-monsoon risk score from June/July departures, with per-feature explanation",
    ("post", "/api/ml/anomaly"): "Is this month's rainfall unusual? (Isolation Forest)",
    ("get", "/api/ml/models"): "Model versions, training data hash, and all evaluation metrics",
    ("post", "/api/auth/register"): "Create a citizen or organization account (returns a session token)",
    ("post", "/api/auth/login"): "Log in (returns a session token)",
    ("post", "/api/auth/logout"): "End this session",
    ("get", "/api/auth/me"): "The logged-in account",
    ("get", "/api/reports"): "Community reports, newest first; filter by status or category",
    ("post", "/api/reports"): "Submit a report (category, area or map point, description, optional photo)",
    ("get", "/api/reports/{rid}"): "One report with its status history",
    ("get", "/api/reports/{rid}/photo"): "The report's resized photo",
    ("get", "/api/hotspots"): "Report counts per area and per ward (last N days) and average tanker price",
    ("get", "/api/treated-water"): "Open treated-water offers and requests",
    ("post", "/api/treated-water/offers"): "Offer treated water (organization or admin)",
    ("post", "/api/treated-water/requests"): "Request treated water (any logged-in user)",
    ("delete", "/api/treated-water/offers/{oid}"): "Close an offer (owner or admin)",
    ("delete", "/api/treated-water/requests/{rid}"): "Close a request (owner or admin)",
    ("get", "/api/matches"): "Ranked offers for each open request, with filters, score parts, reasons and savings",
    ("post", "/api/ai/lab-report"): "AI reads values from a lab-report photo (only when an AI key is configured)",
    ("get", "/api/admin/overview"): "Admin dashboard data: reports by status, risk, warnings, freshness, health, ML, activity",
    ("get", "/api/admin/reports"): "All reports with allowed status transitions",
    ("patch", "/api/admin/reports/{rid}"): "Change a report's status (state machine enforced, audit-logged)",
    ("post", "/api/admin/reservoir-readings"): "Add a reservoir reading with its source (ingestion interface)",
    ("post", "/api/admin/lake-observations"): "Add a lake quality observation with its source",
    ("get", "/api/admin/audit-logs"): "Audit log of admin and account actions",
    ("get", "/api/admin/users"): "Accounts (no password data)",
    ("get", "/api/admin/predictions"): "Logged model predictions",
}
